/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 
#include <cmath>
#include "Analysis/BackgroundModel/interface/RooPhaseSpacePol4.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

using namespace analysis::backgroundmodel;


ClassImp(RooPhaseSpacePol4) 

RooPhaseSpacePol4::RooPhaseSpacePol4(const char *name, const char *title, 
                        RooAbsReal& x) :
  RooAbsPdf(name, title),
  x_("x", "x", this, x)
{ 
} 


RooPhaseSpacePol4::RooPhaseSpacePol4(const RooPhaseSpacePol4& other, const char* name) :  
   RooAbsPdf(other,name), 
   x_("x", this, other.x_)
{ 
} 


TObject* RooPhaseSpacePol4::clone(const char* newname) const {
  return new RooPhaseSpacePol4(*this, newname);
}


double RooPhaseSpacePol4::evaluate() const 
{ 
   double result = 0.0;
   if(x_ <= 400.) 
	result = 0.0;
   if(x_ > 400. && x_ < 1400.) 
   	result = -2.5189 + 0.0131174*x_ - 2.06204e-05*pow(x_,2) + 1.40909e-08*pow(x_,3) - 3.42048e-12*pow(x_,4);
   if(x_ >= 1400.) 
	result = 1.0;

   return result; 
} 



